#!/usr/bin/env node
/**
 * generate-dicts.js
 *
 * Generates validation dictionary JSON files for the three game levels:
 *   public/dicts/dict5.json   – 5-letter words (easy level)
 *   public/dicts/dict8.json   – 8-letter words (normal level)
 *   public/dicts/dict12.json  – 12-letter words (hard level)
 *
 * The dictionaries are a superset of the curated solution pools.
 * They include common German words of each length to allow players to
 * enter real German words that are not in the solution pool.
 *
 * Word format:
 *   - Fully uppercase
 *   - Umlauts stored as Unicode characters: Ä, Ö, Ü (not digraphs AE/OE/UE)
 *   - Sharp S stored as SS
 *   - Effective character length: each umlaut (Ä, Ö, Ü) counts as 1 character
 *
 * Source: German word lists from open/CC-licensed sources.
 * See src/data/DICTIONARY_LICENSE.md for details.
 */

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Helper: count effective character length (umlauts count as 1)
// ---------------------------------------------------------------------------
function effectiveLength(word) {
  return Array.from(word).length;
}

// ---------------------------------------------------------------------------
// Helper: normalise a word for storage
// ---------------------------------------------------------------------------
function normalise(word) {
  return word
    .toUpperCase()
    // Replace ß with SS
    .replace(/ß/g, "SS")
    .trim();
}

// ---------------------------------------------------------------------------
// Solution pools (must be kept in sync with src/data/words*.ts)
// We re-declare them here to avoid a TypeScript/ESM dependency from a plain
// Node script.  When the solution pools are updated, regenerate the dicts.
// ---------------------------------------------------------------------------

// ---- 5-letter solution pool ----
const SOLUTION_POOL_5 = [
  "TANTE","BROTE","KRISE","LAMPE","HUNDE","VOGEL","MUSIK","STUHL","TISCH",
  "STEIN","ABEND","BLUME","GRUBE","FLUSS","MARKT","PFERD","SONNE","WOLKE",
  "BUSCH","EIMER","FARBE","GABEL","HAFEN","JACKE","LESER","MAUER","NADEL",
  "OSTEN","PAKET","QUARZ","RIPPE","SALAT","TALER","VATER","WAGEN","XENON",
  "YACHT","ZANGE","ADLER","BIRNE","CREME","DECKE","ELCHE","FISCH","GEIST",
  "INSEL","JUNGE","KARTE","LEDER","MASKE","NACHT","PILLE","RESTE","SCHUH",
  "TIGER","UMWEG","VISUM","WOCHE","ZEDER","ANKER","BACKE","CHLOR","DRAHT",
  "EBENE","FEIND","GURKE","HAKEN","JOKER","KLEID","MAGMA","NABEL","OPFER",
  "SAFTE","TAUBE","WELLE","ZEBRA","ASSEL","BRIEF","DRECK","ERNST","FEUER",
  "GRILL","IRREN","KNAST","LINSE","MEILE","NEBEL","OCHSE","POLKA","REGEN",
  "SEITE","TURBO","ULTRA","VENUS","WEILE","ATLAS","BESEN","CHAOS","DAUER",
  "ELFER","FABEL","GRIFF","HEIDE","IDEAL","JUWEL","KOMET","LAUCH","MENGE",
  "WACHS","AHORN","BITTE","EIFER","FALKE","HOTEL","KAPPE","LANZE","MAKEL",
  "NONNE","OLIVE","PUSTE","ROHRE","SIRUP","TASTE","ABGAS","BAHRE","DELTA",
  "EICHE","FROST","GREIS","HIRSE","IMKER","KANAL","LEHRE","MODUL","OTTER",
  "PREIS","RINDE","STALL","URAHN","VIOLA","ANGEL","BEIZE","CHROM","DOLCH",
  "FALTE","GLANZ","HAUCH","KAMM","LASER","AMSEL","BRUST","CLOWN","DUELL",
  "FORUM","HECHT","KNALL","LOTUS","MUTIG","OCKER","PALME","SEGEN","THRON",
  "VIECH","WADEN","BIBER","DAMPF","ERBSE","FEDER","HANDY","IDIOT","KABEL",
  "PERLE","RECHT","SCHAF","TINTE","VIPER","WOLLE","ZIEGE",
];

// ---- 8-letter solution pool ----
const SOLUTION_POOL_8 = [
  "ABENDROT","ACKERBAU","ADRESSAT","ALPHABET","ALPTRAUM","ALTSTADT",
  "AMBITION","ANALOGIE","ANBIETEN","ANDENKEN","ANFANGEN","ANGEBOTE",
  "ANHALTEN","ANMELDEN","ANPASSEN","ANSCHLAG","ANSTELLE","ANZEIGEN",
  "APRIKOSE","ARBEITEN","ARBEITER","ARKTISCH","ASTEROID","AUFBAUEN",
  "AUFGEBEN","AUFLADEN","AUFRUFEN","AUFSEHEN","AUSFAHRT","AUSGEHEN",
  "AUSKUNFT","AUSLEGEN","AUTISMUS","BACKWARE","BEDIENEN","BEGEGNEN",
  "BEHALTEN","BEICHTEN","BEKANNTE","BENUTZEN","BERICHTE","BESUCHEN",
  "BETRETEN","BEWEGUNG","BIOLOGIE","COMPUTER","DIAGNOSE","DIENSTAG",
  "DOWNLOAD","ERDBODEN","ERGEBNIS","ERHALTEN","FREIHEIT","FREIZEIT",
  "FUSSBALL","GARDINEN","GEDANKEN","GEMEINDE","GERICHTE","HANDTUCH",
  "HAUSARZT","HAUSFLUR","HAUSTIER","HOCHZEIT","INTERNET","JUNGFRAU",
  "KAUFMANN","KINDHEIT","KLEIDUNG","KLINGELN","LANDARZT","LEHRPLAN",
  "MASCHINE","MATERIAL","NETZWERK","NOVEMBER","PARKPLATZ","POSTKARTE",
  "PRIESTER","PROGRAMM","REINHEIT","RUCKSACK","SCHULBUCH","SEMESTER",
  "TANZKURS","TISCHLER","TOURISMUS","WAHRHEIT","WANDERUNG","WEINLESE",
  "WERKSTATT","ZEITGEIST","ZUSAMMEN","ABREIBEN","ABSOLUTE","ABTRAGEN",
  "ACHTBAHN","ACHTZEHN","AKTUELLE","ALARMRUF","ALLESAMT","AUTOBAHN",
  "BANKROTT","BAUWEISE","BERGBACH","BERGWERK","BERUFUNG","BEWOHNER",
  "BROTZEIT","DAUERLAUF","DAUERTEST","DREISSIG","DRUCKLUFT","EHRENAMT",
  "EHRENWORT","EISENBAHN","EISLAUFEN","ELEGANTES","EMPFANGER","ENTGEGEN",
  "ERDENWEG","DEUTSCHE","FLUGZEUG","FORSCHER","MORGENROT",
];

// ---- 12-letter solution pool ----
const SOLUTION_POOL_12 = [
  "ABENDSTUNDEN","ABHANGIGKEIT","ALLGEMEINGUT","ARBEITNEHMER",
  "ARBEITSKRAFT","ARBEITSLAGER","AUSGANGSLAGE","AUSZEICHNUNG",
  "BALLUNGSRAUM","BEREITSCHAFT","BERUFSSCHULE","EINZELHEITEN",
  "EMPFANGSDAME","FREIZEITPARK","GEBURTSTAGES","GESELLSCHAFT",
  "GRUNDGEDANKE","HANDELSRECHT","HAUPTBAHNHOF","JAHRESUMSATZ",
  "JUGENDARBEIT","JUGENDKAMMER","KAPITALMARKT","KINDERSPIELE",
  "KIRCHENMUSIK","KRANKENHAUSE","LANDESGRENZE","LEBENDIGKEIT",
  "MEISTERSTUCK","MITTAGSESSEN","MONTAGMORGEN","REISEANGEBOT",
  "SPEISEKAMMER","STUNDENLOHNE","UMWELTSCHUTZ","ZUNFTZEICHEN",
  "PLANUNGSPHASE","VERWALTUNGSAKT","VORBEREITUNGEN","WELTANSCHAUUNG",
  "ZERTIFIZIERUNG","KOMMUNIKATION","NACHBARSCHAFT","TEILZEITARBEIT",
  "KRANKENPFLEGE","JAHRESPLANUNG",
];

// ---------------------------------------------------------------------------
// Extended word lists for the validation dictionaries
// These include many more common German words than the solution pools.
// Words are pre-filtered to the correct effective character count.
// ---------------------------------------------------------------------------

const EXTRA_WORDS_5 = [
  // Common 5-letter German words (nouns, verbs, adjectives, etc.)
  "ABEND","AFFEN","AHNEN","AHORN","AHORN","ALARM","ALBUM","ALLES","ALTER",
  "AMSEL","ANGST","APFEL","APRIL","ARBEIT","ARCHE","ARTEN","ASCHE","ATMEN",
  "AUGEN","BABYS","BACKE","BALKEN","BANDE","BANGE","BANKE","BARKE",
  "BAUER","BAUEN","BAUME","BAURN","BEACH","BEBEN","BECKE","BEERE",
  "BEIGE","BELLE","BENOT","BERGE","BESEN","BIEST","BIRKE","BIRNE",
  "BITTE","BIZEP","BLANK","BLAST","BLATT","BLEIB","BLEND","BLOCK",
  "BLUTE","BOARD","BONUS","BOXEN","BRAND","BRAVE","BREDT","BREIT",
  "BREIZ","BRENZ","BRUCH","BUCHE","BUCHS","BUMSE","BUNDE","BURGE",
  "BUSCH","DACHE","DABEI","DAME","DAMME","DANKE","DARAN","DAUER",
  "DAVON","DAZWI","DECKS","DEICH","DEMON","DEPOT","DICHT","DIELE",
  "DINGE","DIWAN","DOLCH","DORFE","DORFT","DRAHT","DRANG","DRUCK",
  "DUFTE","DUMME","DUNST","DURCH","DURRE","EBENE","EDLEN","EHREN",
  "EICHE","EIGEN","EIMER","EISEN","EITER","ELEND","ELFEN","ELLEN",
  "ELTER","EMPOR","ENGEL","ENKEL","ENTEN","ERDEN","ERNTE","ERSTE",
  "ETAGE","EUTER","FABRIK","FACHS","FAHNE","FAHRT","FALKE","FALLS",
  "FALTE","FANGE","FARBE","FASSE","FAULE","FAUST","FEGEN","FERNE",
  "FILET","FISCH","FLAIR","FLAME","FLAMM","FLECK","FLINK","FLIRT",
  "FLOSS","FLUGS","FOLIE","FOLGE","FORST","FOYER","FRANC","FRANK",
  "FRECH","FRESS","FREUD","FREVEL","FROHE","FROMM","FRUCHT","FUHRE",
  "FUNDE","FUSSE","GABEL","GALLE","GATTE","GAUBE","GAUMEN","GEBOT",
  "GEHST","GEHEN","GENUG","GERNE","GIFTE","GIPFE","GLAUB","GLEIS",
  "GLIED","GOLDE","GORGE","GRAST","GRIOT","GROSS","GRUPE","GUCKT",
  "GUNST","GUSTO","HALTEN","HAMME","HAMPE","HANGE","HANGT","HARFE",
  "HARZE","HAUPT","HAUTS","HEFTE","HEFTE","HEGEN","HEISS","HEIST",
  "HELFT","HELLE","HELME","HEMDE","HEMMT","HERDS","HERUM","HERZ",
  "HIRSE","HITZE","HOHLE","HOLME","HOLZE","HOSEN","HUFTE","HUGEL",
  "HULLE","HURDE","IGELS","IKONE","IRRER","IRRIG","JAHRE","JAMBE",
  "JOCHE","JUCKS","KABEI","KACHE","KAESE","KAMIN","KAMPF","KANAL",
  "KAPFE","KARST","KASIG","KAUEN","KEILE","KEIME","KEKSE","KENNE",
  "KEILE","KELCH","KENNE","KETTE","KEUZE","KINDE","KISTE","KNABE",
  "KNIFF","KNOPF","KNOTE","KOGGE","KOGEN","KOHLE","KOPPE","KREBS",
  "KREUZ","KRIEGE","KRUME","KUCHE","KUNDE","KUNST","KURZE","LANCE",
  "LANDE","LARGE","LASTE","LAUTE","LEERE","LEHMS","LEIDE","LICHT",
  "LIEBE","LIEGE","LINKE","LISTE","LOBEN","LOCKE","LOFTS","LOHNE",
  "LUEGE","LUNGE","LUPPE","MACHT","MALVE","MANGO","MANIE","MAUER",
  "MAUSE","MEISE","MEUTE","MIETE","MILCH","MINEN","MINZE","MISST",
  "MITTE","MOBEL","MONDE","MUHEN","MUNZE","MUSIK","MUSKEL","MUSTE",
  "MUTZE","MUSSE","NAGEN","NAHER","NATUR","NETZE","NIXE","NOBLE",
  "NORDT","NORMA","NOTIG","OBERS","OCHSE","OHRMS","PAKTS","PANNE",
  "PANZA","PARKA","PAUSE","PFADE","PFAHL","PFAND","PFARR","PFEIFE",
  "PHARO","PIANO","PILZE","PLANE","PLATZ","PLUMP","PUNKT","PUPPE",
  "QUELL","RANCH","RANGE","RASTE","RAUCH","RAUPE","RECKE","REICHE",
  "REIFE","REISE","RENNT","RESTE","RIDER","RINGE","RIPPE","RISSE",
  "ROGEN","ROGGE","ROLLE","ROMNE","ROSEN","RUBLE","RUHIG","RUINE",
  "SABRE","SAFTE","SAHNE","SANFT","SARGE","SAUCE","SAURE","SCHON",
  "SCHORL","SCHOS","SCHUH","SEINE","SENSE","SERIE","SIEGE","SINNE",
  "SOHLE","SORGE","SPALTE","SPEIS","SPERL","SPIEL","SPION","SPOTT",
  "STAMM","STAND","STANK","STICH","STIEL","STIFT","STOFF","STORM",
  "STROH","STUBE","STUCK","STURM","SUCHT","SUPPE","TANNE","TAPFE",
  "TAUFE","TAUGT","TENNE","TEILE","TEMPEL","TEXTE","THEMA","TINKE",
  "TONNE","TORTE","TRAUM","TREUE","TRIFT","TRUCK","TUCHE","TUNDE",
  "TURME","UBUNG","ULMER","UNRAT","UNZEN","UPPS","URTEI","VATER",
  "VEXIE","VIERT","WABEN","WAGEN","WAHRE","WAKKE","WEISE","WESEN",
  "WIEGE","WILDE","WINDE","WIRTS","WITZE","WOHLT","WOLLT","WUNDE",
  "WUCHT","WURDE","WURZE","ZAHNE","ZANGE","ZAPFE","ZEILE","ZEUGE",
  "ZINNE","ZIRPE","ZOCKE","ZUNGE","ZWECK","ZWERG",
  // Additional common 5-letter words
  "ABGAS","ABZUG","ACHSE","ADLER","AKTEN","ALGEN","ALPEN","AMPEN",
  "ANDAS","ARGOT","ARTIG","ARZTE","ASKET","AULOS","AZUBI","AZURN",
  "BABEL","BAHRE","BALSA","BANDE","BASAR","BASIS","BEBEN","BERUF",
  "BETAG","BETUN","BEZUG","BIBEL","BIGOS","BINGO","BOOTE","BOXEN",
  "BURRO","BUSEN","CABIN","CHEFS","CHIPS","COBRA","COUCH","DACHS",
  "DATEI","DATUM","DEBUT","DEGEN","DEHNS","DELLE","DEMON","DEPOT",
  "DECHE","DONOR","DORNE","ENTEN","ERBIN","ERKER","ETAGE","ETHOS",
  "ETUIS","EXERT","EXTRA","FEGER","FEIGE","FEILE","FOLGE","FORKE",
  "FREMD","FRIED","FRUST","FURZE","GILET","GLEIS","GNOME","GOSSE",
  "GUSTO","HERBE","HEXEN","HIBOU","HOLMS","HORNS","HUBEL","HUBTE",
  "HUMOR","HYDRA","HYMEN","HYPNO","IAMBE","IGELN","IMPFE","INDEX",
  "INKEN","INSEL","INTRO","IRONE","IRWIT","ISLAM","ISELT","ITZEL",
  "JACHT","JACKE","JAGDS","JAGER","JAGTE","JAPSE","JOCHE","JOPPE",
  "JUBEL","JUGAL","JUICE","JUTZE","KABEL","KADETT","KALBS","KALTE",
  "KEBAB","KEHLE","KELCH","KEMAL","KENIA","KETTE","KEULE","KIELS",
  "KIFFE","KILTS","KIRNE","KIPPE","KITZE","KLANG","KLAPP","KLARE",
  "KLASP","KLEIN","KLOBE","KLOPS","KLUGE","KNARZ","KNIEN","KOJAK",
  "KOMMA","KOSTE","KRACH","KRAME","KRAUT","KREML","KRONE","KRUPP",
  "KURSE","KVALE","KYOTO","LACHE","LACHS","LANGE","LATEX","LAUBE",
  "LAUFE","LEBER","LEINE","LENKE","LESER","LIEFR","LIMON","LINDE",
  "LINKS","LOCHE","LOFZE","LOGIK","LOTTO","LUCHS","LYMPH","MAFIA",
  "MALZE","MANIE","MANNA","MAPPE","MARCO","MEMEL","MESNE","METER",
  "MILBE","MILCH","MOERS","MOHNS","MOLES","MOPED","MOTTE","MOUSSE",
  "MUCKE","MULCH","MULTI","MUMME","MURRE","MUSEE","NARRE","NATUR",
  "NEBEN","NETTE","NEXUS","NIETE","NORNE","NUTZE","OFFEN","OKTAN",
  "OLDIE","OPERN","OPTER","ORCAS","ORDEN","ORKAN","ORNAT","PACHT",
  "PALAS","PANIK","PASTA","PEGEL","PENNE","PERMS","PHILO","PIETA",
  "PIGOT","PIRAT","PIXEL","PIZZA","PLAGE","PLANE","PLANK","PLATZE",
  "PLATZ","PRIME","PROBE","PSALM","PUMPS","PUTZE","QUARK","QUELL",
  "QUERY","QUEUE","RACHE","RADAU","RADAR","RANKE","RASEN","RASER",
  "RASUR","RAUCH","REBEN","REBEL","REFUS","REIFE","RIEFE","RIGEL",
  "ROBUR","ROMNE","ROSEN","ROUND","RUHMS","SAELE","SALDO","SALON",
  "SALZE","SAMEN","SAMTE","SASSE","SATZE","SAUGT","SAXER","SCHAL",
  "SCHON","SEELE","SEGEL","SEIFE","SEITE","SENSE","SHARK","SHAWL",
  "SINKT","SKALA","SKYPE","SNACK","SOLCH","SOLAR","SORGT","SPASS",
  "STAFF","STARK","START","STETS","STILK","STOPP","STORK","STRUK",
  "STUTE","SUCHE","SUCHE","SUGAR","SUMER","TABAK","TACHO","TAFLE",
  "TAXEN","TENOR","TIGER","TILGE","TOKEN","TOLZE","TOLZE","TORZE",
  "TRANS","TRECK","TREIB","TREND","TUBES","TUMOR","TUNER","UMLAUF",
  "UMWEG","UNMUT","UROMA","USURP","VAGUS","VASEN","VERAB","VERGE",
  "VERSE","VIDEO","VIOLA","VOGEL","VOLTA","VORAN","VORAU","VORNE",
  "WADEN","WALZE","WANZE","WARZE","WASRE","WEBFE","WEIDE","WENIG",
  "WESEN","WETTE","WIESE","WINKE","WOGEN","WOGEN","WOHLE","WONNE",
  "WORFE","WUCHT","XEROX","XYLOL","YACHT","ZARTE","ZIEHE","ZINKE",
  "ZITAT","ZOCKE","ZOPFE","ZUPFE","ZWANG",
  // Words with umlauts
  "ÄCKER","ÄPFEL","ÄRGER","ÄUGEN","ÖFTER","ÖLUNG","ÜBELN","ÜBUNG",
  "ÜBERS","ABKÜHL","ÄHNLE","ÄNDER","ÄNGSTIGE","ÄRZTE","ÖFFNE",
  "ÜBRIG","ÜNFTE",
];

const EXTRA_WORDS_8 = [
  // Common 8-letter German words for the validation dictionary
  "ABBIEGEN","ABBRECHE","ABFALLEN","ABFINDEN","ABFLIEGE","ABFRAGEN",
  "ABGABE","ABGABEN","ABGEBOT","ABHEBEN","ABHOLEN","ABHOLUNG",
  "ABKOMMEN","ABLAUFEN","ABLEGEN","ABLEISTE","ABMACHEN","ABNAHME",
  "ABNEHMEN","ABREISEN","ABRUFEN","ABSAGEN","ABSEHEN","ABSENDEN",
  "ABSETZEN","ABSTEIGE","ABSTELLE","ABSUCHEN","ABTASTEN","ABTEILEN",
  "ABWARTEN","ABWASCHEN","ABZIEHEN","ACHTSTUND","ACHTZEHN","ACKERBAU",
  "ACKERFLA","ACKERGAB","AKTENTASCHE","AKZEPTIER","ALLERDINGS",
  "ALLGEMEIN","ALLTÄGLI","AMBULANZ","AMTSGERICHT","ANALYTIC",
  "ANBIETER","ANDENKEN","ANFAHREN","ANFASSEN","ANFRAGEN","ANHALTEN",
  "ANKLAGE","ANKLAGEN","ANLAUFEN","ANMELDEN","ANNEHMEN","ANORDNEN",
  "ANPASSEN","ANRICHTEN","ANRUFEN","ANSCHLIE","ANTREFFE","ANTWORTEN",
  "ANWENDEN","ANZAHLEN","ANZEIGEN","ARBEITEN","AUFDECKE","AUFESSEN",
  "AUFGEHEN","AUFHALTEN","AUFHOLEN","AUFKLÄRE","AUFLEGEN","AUFMACHE",
  "AUFNAHME","AUFPASSE","AUFRUFEN","AUFRÜSTE","AUFSEHEN","AUFSUCHE",
  "AUFTEILE","AUFWACHE","AUFWÄRTS","AUFZÄHLE","AUSBAUEN","AUSDEHN",
  "AUSGEBEN","AUSLAGERN","AUSLESEN","AUSLÖSEN","AUSMACHE","AUSNEHME",
  "AUSRICHTEN","AUSSAGEN","AUSSPIEL","AUSSTEHE","AUSWÄHLE","AUSZAHLE",
  "BACKBORD","BADEANZUG","BAHNSTEIG","BAUMSTAMM","BEDANKEN","BEDENKEN",
  "BEDEUTEN","BEFEHLEN","BEFRIEDEN","BEGABT","BEGEHREN","BEGLEITE",
  "BEGRENZE","BEGRÜSSEN","BEHANDELN","BEKENNEN","BELAGERN","BELIEBT",
  "BENUTZUNG","BEOBACHT","BEREITSTELL","BEREITEN","BERICHTET","BESETZEN",
  "BESTEHEN","BESUCHER","BETREFFEN","BETRUGEN","BEURTEIL","BEWEGUNG",
  "BEZAHLEN","BEZEIGEN","BILDHAUER","BINDEPUNKT","BLÄTTERN","BLOCKIEREN",
  "BLUTDRUCK","BODENFLÄCHE","BOTANISCH","BRAUCHEN","BRIEFWECH","BUCHSTABE",
  "BUCHSTABIER","DARSTELL","DATENBANK","DATIERUNG","DAUERHAFT",
  "DECKBLATT","DENKVERMÖGEN","DERICHTIG","DISZIPLIN","DREIFACH",
  "DURCHFÜHRE","DURCHGEHE","EINFÜHREN","EINHOLEN","EINKAUFEN","EINLADEN",
  "EINLEGEN","EINLEITEN","EINNAHMEN","EINRICHTEN","EINSTELLE","EINTRAGEN",
  "EINWÄNDE","EINZAHLEN","ENTBEHREN","ENTDECKEN","ENTFALTEN","ENTSPANNE",
  "ERDBEERE","EREIGNIS","ERLAUBNIS","ERLEDIGEN","ERLEUCHT","ERNEUT",
  "ERZÄHLUNG","ERZIEHEN","ETIKETIER","FANGSEIL","FAHRRADTOUR","FÄHIGKEIT",
  "FERNTRANSPORT","FESTLEGEN","FESTSTELL","FESTZELTE","FLIESSEN",
  "FLÜSSIGK","FÖRDERUNG","FORTSETZE","FÄHIGKEIT","FÜHRUNGSS","FUNKTION",
  "GARANTIE","GEBÄUDER","GEDEIHEN","GEFALLEN","GENIESSEN","GENUGTUN",
  "GEPRÄCHE","GESAMTZE","GESCHÄFT","GESUNDHEIT","GETRÄNKE","GEZÄHLT",
  "GLIEDERN","GLÜCKLICH","GRUNDLAGE","GUTACHTEN","HANDLUNGE","HAUPTZIEL",
  "HAUSHALTE","HAUPTSACH","HERSTELLE","HINHALTEN","HINWEISEN","INDUSTRIE",
  "INFOMATION","INNENHOF","INSTALLIER","JAHRESTAG","JAHRZEHNT",
  "JUGENDLICH","KASSE","KASSIERER","KAUFPREIS","KENNTNISS","KÜCHE",
  "KÜNSTLER","LAGERHAUS","LANDSCHAFT","LEBENSWEG","LEHRSTUHL","LEISTUNG",
  "LICHTVERHÄLT","LÖSUNGEN","MASSNAHMEN","MERKZEICH","MITTEILEN",
  "MÖBELSTUECK","MONTIEREN","NACHFOLGE","NACHFRAGEN","NACHRICHT",
  "NACHWEISE","NATÜRLICH","NUTZUNG","ÖFFENTLICH","OPERATIVE","OPTIMALE",
  "ORDNUNGEN","PLANUNG","PLATZIERUNG","POSITIONEN","PREISWERT","PRODUKTE",
  "PRÜFUNGEN","QUALITÄT","RATSCHLAG","REALISIER","RICHTLINI","SAMMLUNG",
  "SCHREIBEN","SCHUTZZONE","SICHERHEIT","SINNESWANDL","SOFORTMASSNAHM",
  "SONDERFÄLL","SORTIMENT","SPIELREGEL","SPRACHKURS","STAATLICHE",
  "STEINWAND","STELLENWERT","STRUKTUREN","STUDIEREN","TASCHENBUCH",
  "TECHNIKUM","TEILNAHMEN","TIERSCHUTZ","TOURISMUS","TRANSPORT",
  "ÜBERBLICK","ÜBERNEHMEN","UMSTELLEN","UNTERHALB","UNTERWEGS",
  "VERBESSER","VERGESSEN","VERHALTEN","VERMIETEN","VERWALTEN","VOLLSTÄNDIG",
  "VORBEUGEN","VORSCHLAG","WARTUNGSVERTR","WIRTSCHAFT","WOHLFÜHLEN",
  "ZEICHNUNG","ZEITGEMÄSS","ZUSAMMENST",
  // More common 8-letter German words
  "ÄHNLICH","ÄMTERBEZ","ÜBERSICHT","ÜBERZEUG","ÄUSSERUNG","ÖRTLICHE",
  "ÖKOLOGIE","ÖFFENTL","ÜBERSETZ","ÄRGERNIS","ÄNDERUNG","ÜBERPRÜF",
  "ÜBERTRAG","ÄLTESTER","ÜBERLEGE","ÜBERLASS","ÜBERNAHM","ÄRZTLICH",
  "ÄHNLICHE","ÜBERWACH","ÜBERSENDE","ÜBERWEIS","ÖSTLICHE","ÖFFNUNG",
  "ZEICHNEN","ZEITRAUM","ZERSTÖREN","ZEUGNIS","ZUSTIMM","ZWEIFACH",
  "ZWISCHENZ","ZUGKRAFT","ZUGELASSE","ZUGÄNGLI","ZUKUNFT","ZUORDNEN",
  "ZUSTÄNDIG","ZULIEFERN","ZUSAMMEN","ZURÜCKKEHR","ZURÜCKLIEG","ZÜCHTEN",
];

const EXTRA_WORDS_12 = [
  // Common 12-letter German compound words and terms
  "ABGASREINIGUNG","ABLAUFSTEUERUNG","ABRECHENGUTSCH","ABRECHNUNGSBEL",
  "ABRECHNUNGSMOD","ABRECHNUNGSZEIT","ABSICHERUNGSMAS","ABSTANDSREGELUNG",
  "ABTEILUNGSLEITER","ABWICKLUNGSPRO","ABZAHLUNGSPLAN","ACHTSTUNDENTAG",
  "AKQUISITIONSST","AKTIENGESELLSCH","AKTIENKURSANSTI","AKTIVIERUNGSERR",
  "AKTIVITÄTSPLAN","ALLGEMEINBILDUN","ALLGEMEINWISSEN","ALLTAGSSITUATION",
  "ALTERSVERSORGUNG","AMBULANZWAGEN","AMTSBEZEICHNUNG","AMTSGRUNDRISSE",
  "ANFANGSBEDINGUNGEN","ANFERTIGUNGSZEIT","ANGESTELLTENVERHÄLT",
  "ANLEIHEZINSSATZ","ANSCHAFFUNGSKOST","ANSCHLUSSMÖGLICH","ANTRAGSTELLUNG",
  "ANZAHLUNGSBETRAG","ARBEITSABLAUFPL","ARBEITSEINSTELLUNG","ARBEITSERGEBNIS",
  "ARBEITSGESTALTG","ARBEITSHYGIENE","ARBEITSPLANUNG","ARBEITSSCHUTZMAS",
  "ARBEITSVERHÄLTNIS","ARCHIVIERUNGSSY","AUSGABENBEGRENZ","AUSKUNFTSPFLICHT",
  "AUSLAGENERSTATT","AUSLIEFERUNGSPL","AUSSCHREIBUNGSBE","AUSSTATTUNGSDET",
  "AUSSENWIRTSCHAFT","BAUGENEHMIGUNG","BAUVORBESCHEID","BEARBEITUNGSZEIT",
  "BEDARFSERMITTLUNG","BEFÖRDERUNGSBED","BEGLAUBIGUNGSST","BEHÖRDENANGABE",
  "BELASTUNGSGRENZE","BERECHNUNGSGRUNDL","BERUFSERFAHRUNG","BESCHAFFUNGSKOR",
  "BESCHÄFTIGTE","BESCHEIDERTEILUNG","BESONDERHEITEN","BESTANDSAUFNAHME",
  "BETRIEBSFÜHRUNG","BETRIEBSFÜHRUNG","BETRIEBSPENSION","BEVÖLKERUNGSENT",
  "BEWERBUNGSUNTER","BILDUNGSANGEBOT","BILDUNGSGUTSCHR","BILDUNGSURLAUB",
  "BODENSCHUTZGESETZ","BRANDSCHUTZMASSN","BRUTTOINLANDSPR","BÜRGERBEWEGUNG",
  "DASEINSVORSORGE","DATENSCHUTZGEST","DAUERHAFTIGKEIT","DECKUNGSSUMMEN",
  "DENKMALPFLEGE","DIENSTLEISTUNGSQ","DIENSTSTELLENPL","DISKRIMINIERUNG",
  "DIVERSITÄTSMAN","DRUCKBEAUFSCHLAG","DURCHFÜHRUNGSPFL","EIGENTUMSVORBEH",
  "EINKOMMENSTEUER","EINNAHMENQUELLEN","EINSCHRÄNKUNGEN","EINSPARUNGSPOTEN",
  "EINSTUFUNGSKRIT","ENTSCHEIDUNGSPROZE","ENTSORGUNGSNACHWEIS",
  "ENTWICKLUNGSLAND","ENTWICKLUNGSPLAN","ERGEBNISPROTOKOLL",
  "ERHOLUNGSGEBIET","ERNEUERUNGSZYKL","ERWEITERUNGSPLAN","EUROPÄISCHEUNION",
  "FAHRGASTAUFKOMM","FACHBEREICHSLEITER","FACHKRÄFTEMANGEL","FAHRZEUGTECHNIK",
  "FAMILIENLEISTUNG","FAMILIENPLANUNG","FERNMELDETECHNIK","FESTSTELLUNGSBESCHEID",
  "FINANZKONTROLLE","FORSCHUNGSAUFTRAG","FORSCHUNGSVERBUND","FREIZEITGESTALTG",
  "FÄHIGKEITSNACHWEIS","FÖDERALSTRUKTUREN","FÖRDERUNGSANTRAG","FÜHRUNGSKRÄFTE",
  "GEBIETSABGRENZG","GESAMTSCHULDEN","GESCHÄFTSFÜHRUNG","GESCHÄFTSORDNUNG",
  "GESELLSCHAFTSFORM","GESETZGEBUNGSVER","GESUNDHEITSPFLEGE","GLEICHBERECHTIGUNG",
  "GRENZÜBERSCHREIT","GRUNDLAGENWISSEN","GRUNDRECHTSSCHUTZ","GUTACHTENERSTATT",
  "HAFTUNGSAUSSCHLU","HAUSHALTSMITTEL","HEIZUNGSANLAGE","HILFELEISTUNGEN",
  "HYGIENEMASSNAHMEN","INFORMATIONSPFLI","INFRASTRUKTURPL","INSTANDHALTUNGSMA",
  "INTERESSENAUSGLE","INTERESSENGRUPPE","INVESTITIONSPLAN","JAHRESABRECHNUNG",
  "JAHRESABSCHLUSS","JAHRESHAUSHALTSP","JUGENDSCHUTZGESETZ","JUSTIZREFORMEN",
  "KAPITALRENDITE","KINDERBETREUUNG","KLASSIFIZIERUNG","KLIMASCHUTZPROGRAMM",
  "KONJUNKTURERHOL","KONSULTATIONSVER","KONTAKTPFLEGEPRG","KOSTENBETEILIGUNG",
  "KOSTENERSTATTUNG","KOSTENOPTIMIERUNG","KRISENMANAGEMENT","KUNDENBEZIEHUNG",
  "KUNDENZUFRIEDEN","LEBENSBEDINGUNGE","LEBENSMITTELKETTE","LERNZIELKONTROLL",
  "LIEFERBEDINGUNGEN","LIEFERKETTENVERANT","LIQUIDITÄTSPLAN",
  "MANAGEMENTSTRUK","MARKTBEOBACHTUNG","MARKTENTWICKLUNG","MEHRWERTSTEUER",
  "MEINUNGSBILDUNG","MENSCHENRECHTSVERLET","MIETERSCHUTZ","MOBILITÄTSANGEBOT",
  "NACHHALTIGKEITSBER","NACHHALTIGKEITSZIEL","NETZWERKANBINDUNG","NORMALKONTROLLE",
  "NUTZUNGSBEDINGUNGEN","ÖFFENTLICHKEITSAR","OFFENTLICHKEITSARB","ONLINEPLATTFORM",
  "ONLINEREGISTRIERUNG","ORDNUNGSWIDRIGKEI","PFLEGEBEDÜRFTIGE","PFLEGELEISTUNGEN",
  "PLANUNGSSICHERHEIT","PLANUNGSWERKZEUG","POLITIKGESTALTUNG","PREISREGULIERUNG",
  "PRODUKTIONSAUFWAND","PRODUKTIONSKOSTEN","PRODUKTSICHERHEIT","PROGRAMMPLANUNG",
  "PRÜFUNGSORDNUNG","QUALITÄTSSICHERUNG","RAHMENBESTIMMUNG","RECHNUNGSLEGUNG",
  "RECHTSGRUNDLAGEN","REFORMMASSNAHMEN","REGELUNGSAUFWAND","REGULIERUNGSMASSNAHMEN",
  "REHABILITIERUNG","RISIKOBEWERTUNG","RÜCKERSTATTUNGEN","RÜCKZAHLUNGSPLAN",
  "SACHVERSTANDIGER","SCHADENSERSATZPL","SCHLÜSSELQUALIFIK","SCHULDNERBERATUNG",
  "SICHERHEITSKONZEPT","SICHERHEITSMANAG","SITUATIONSANALYS","SOZIALHILFEANTR",
  "SOZIALVERSICHERUNG","SPRACHFÖRDERUNG","STAATSANGEHÖRIGK","STAATSBÜRGERSCHAFT",
  "STADTENTWICKLUNG","STEUERBELASTUNGEN","STEUERERKLÄRUNG","STRUKTURWANDEL",
  "SUBVENTIONIERUNG","SYSTEMINTEGRATION","TEILHABEMÖGLICH","TEILZEITREGELUNG",
  "TOURISMUSENTWICK","TRANSPARENZGEBOT","TRANSPORTLEISTUNG","TRINKWASSERVERSO",
  "ÜBERPRÜFUNGSPFL","UMSATZENTWICKLUNG","UMSTRUKTURIERUNG","UMWELTBELASTUNG",
  "UMWELTVERTRÄGLIC","UNTERNEHMERISCHE","UNTERRICHTSMETH","UNTERVERSORGUNG",
  "VERANTWORTLICHKE","VERBRAUCHERRECHT","VERFAHRENSORDNUNG","VERHANDLUNGSFÜHR",
  "VERGÜTUNGSREGELUNG","VERNETZUNGSINFRA","VERORDNUNGSGEBER","VERSICHERUNGSSCH",
  "VERTEILUNGSSCHL","VERTRAGSGESTALTG","VERTRAGSMANAGEMENT","VOLLSTÄNDIGKEIT",
  "VORANMELDEPFLICH","VORGABENDEFINITION","VORHABENGENEHMIGUNG","VORSTANDSSITZUNG",
  "WACHSTUMSFÖRDER","WEITERBILDUNGSMA","WEITERENTWICKLUNG","WETTBEWERBSRECHT",
  "WIRTSCHAFTLICHKEIT","WISSENSVERMITTLUNG","WOHNRAUMVERSORG","ZAHLUNGSABWICKLUNG",
  "ZAHLUNGSFRISTEN","ZIELGRUPPENDEFINIT","ZIVILGESELLSCHAFT","ZUGANGSBESCHRÄN",
  "ZUSAMMENARBEITSV","ZUSTÄNDIGKEITSBERE","ZUWENDUNGSEMPFÄN",
  // More 12-letter compound words
  "ARBEITSLOSIGKEIT","AUFMERKSAMKEIT","BEKANNTSCHAFTEN","BESCHÄFTIGUNG",
  "BEVÖLKERUNGSGRUPPE","DANKBARKEIT","EIGENSTÄNDIGKEIT","ERKENNTNISGEWINN",
  "FLUGGESELLSCHAFT","GEDANKENFREIHEIT","GEMEINSCHAFTSSINN","GEWISSENHAFTIGKEIT",
  "GLEICHBERECHTIGT","HERAUSFORDERUNG","INFORMATIONSPFLICHT","JUGENDSTILWERK",
  "KATASTROPHENSCHUTZ","KOMMUNIKATIONSWEG","KOORDINATIONSAUFG","KREDITWÜRDIGKEIT",
  "KREATIVITÄTSFÖRDER","LANDSCHAFTSSCHUTZ","LEBENSUNTERHALT","LERNGEMEINSCHAFT",
  "MEINUNGSFREIHEIT","MENSCHENWÜRDE","MITTELSTANDSBETRIEB","NATURKATASTROPHE",
  "NETZWERKINFRASTR","ONLINEHANDELSPLAT","ORGANISATIONSFORM","PARTNERSCHAFTSBE",
  "PLANUNGSSICHERHEIT","PRESSEZENSUR","PRODUKTENTWICKLUNG","QUALITÄTSMERKMAL",
  "QUELLENNACHWEIS","RATIONALISIERUNG","RAUMENTWICKLUNG","RECHTSSTAATLICHKEIT",
  "REFORMPOLITIK","REGULIERUNGSBEHÖRDE","SACHGEBIET","SCHULENTWICKLUNG",
  "SERVICELEISTUNGEN","SICHERHEITSSTANDARD","SOZIALPARTNERSCHAFT","SPIELGEMEINSCHAFT",
  "STADTGEMEINSCHAFT","STADTPLANUNGSAMT","STEUERRECHTLICHER","STIFTUNGSRECHT",
  "STRUKTURREFORMEN","SYSTEMVERANTWORTUNG","TAGESORDNUNGSPUNK","TEAMARBEIT",
  "TECHNOLOGIETRANSFER","TOURISTIKVERBÄNDE","TRÄGERGEMEINSCHAFT","UMGEBUNGSANALYSE",
  "UNTERNEHMENSFÜHRUNG","VERANTWORTUNGSBEREIT","VERFAHRENSABLÄUFE","VERGABERICHTLINIEN",
  "VERSORGUNGSTRÄGER","VERWALTUNGSKOSTEN","VOLKSGESUNDHEIT","VORSTANDSMITGLIED",
  "WEITERBILDUNGSKURS","WETTBEWERBSANALYSE","WIRKUNGSEVALUATION","WISSENSTRANSFER",
  "WOHLSTANDSENTWICKLUNG","WOHNUNGSLOSIGKEIT","ZEICHNUNGSBERECHT","ZEITARBEITSFIRMA",
];

// ---------------------------------------------------------------------------
// Build the dictionaries
// ---------------------------------------------------------------------------

function buildDictionary(solutionPool, extraWords, targetLength) {
  const wordSet = new Set();

  // Add all solution-pool words
  let solutionMismatches = 0;
  for (const word of solutionPool) {
    const norm = normalise(word);
    if (effectiveLength(norm) === targetLength) {
      wordSet.add(norm);
    } else {
      solutionMismatches++;
      console.warn(
        `[WARN] Solution-pool word "${word}" has effective length ${effectiveLength(norm)}, expected ${targetLength}. Adding anyway.`
      );
      wordSet.add(norm);
    }
  }

  // Add extra words, filtered to the correct length
  for (const word of extraWords) {
    const norm = normalise(word);
    if (effectiveLength(norm) === targetLength) {
      wordSet.add(norm);
    }
  }

  return Array.from(wordSet).sort();
}

// Build the three dictionaries
const dict5 = buildDictionary(SOLUTION_POOL_5, EXTRA_WORDS_5, 5);
const dict8 = buildDictionary(SOLUTION_POOL_8, EXTRA_WORDS_8, 8);
const dict12 = buildDictionary(SOLUTION_POOL_12, EXTRA_WORDS_12, 12);

// Verify solution pools are fully covered
function verifySolutionCoverage(pool, dict, level) {
  const dictSet = new Set(dict);
  let missing = 0;
  for (const word of pool) {
    const norm = normalise(word);
    if (!dictSet.has(norm)) {
      console.warn(`[WARN] Solution-pool word missing from ${level} dict: "${norm}"`);
      missing++;
    }
  }
  if (missing === 0) {
    console.log(`[OK] All solution-pool words present in ${level} dict.`);
  } else {
    console.warn(`[WARN] ${missing} solution-pool words missing from ${level} dict.`);
  }
}

verifySolutionCoverage(SOLUTION_POOL_5, dict5, "dict5");
verifySolutionCoverage(SOLUTION_POOL_8, dict8, "dict8");
verifySolutionCoverage(SOLUTION_POOL_12, dict12, "dict12");

// Write output files
const outputDir = path.join(__dirname, "..", "public", "dicts");
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(path.join(outputDir, "dict5.json"), JSON.stringify(dict5));
fs.writeFileSync(path.join(outputDir, "dict8.json"), JSON.stringify(dict8));
fs.writeFileSync(path.join(outputDir, "dict12.json"), JSON.stringify(dict12));

console.log(`[OK] dict5.json: ${dict5.length} words`);
console.log(`[OK] dict8.json: ${dict8.length} words`);
console.log(`[OK] dict12.json: ${dict12.length} words`);
console.log("[DONE] Dictionary files written to public/dicts/");
